name: 'Oryx Build'
description: 'Oryx Build'
inputs:
  app-location:  # id of input
    description: 'Directory location of the application source code'
    required: false
    default: '/'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.app-location }}