name: Trigger auto deployment for capps-sample-test-snehapar16

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/capps-sample-test-snehapar16-AutoDeployTrigger-3f1b1691-7482-43a2-9afd-25f00a43b786.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CAPPSSAMPLETESTSNEHAPAR16_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: snehaparacr.azurecr.io
          registryUsername: ${{ secrets.CAPPSSAMPLETESTSNEHAPAR16_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CAPPSSAMPLETESTSNEHAPAR16_REGISTRY_PASSWORD }}
          containerAppName: capps-sample-test-snehapar16
          resourceGroup: ca-snehapar-group
          imageToBuild: snehaparacr.azurecr.io/capps-sample-test-snehapar16:${{ github.sha }}
          

     

