name: Trigger auto deployment for snehapar-capp-sample

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/snehapar-capp-sample-AutoDeployTrigger-1c75f141-18ff-4a1b-abc6-3e3faeabea36.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SNEHAPARCAPPSAMPLE_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: snehaparacr.azurecr.io
          registryUsername: ${{ secrets.SNEHAPARCAPPSAMPLE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SNEHAPARCAPPSAMPLE_REGISTRY_PASSWORD }}
          containerAppName: snehapar-capp-sample
          resourceGroup: ca-snehapar-group
          imageToBuild: snehaparacr.azurecr.io/mcr.microsoft.com/k8se/quickstart:${{ github.sha }}
          

     

